App:
  NavTitle: 5ª Ed.USA
  NavTitleShort: 5ª Ed.USA
  NoItemsFound: No se encontraron artículos.
  NoRulesAvailable: No hay reglas disponibles.
  SearchPlaceholder: Buscar reglas
  Locale:
    ShowRules: Mostrar reglas
    ShowFAQ: Mostrar FAQ
    ShowErrata: Mostrar Errata
  Titles:
    Search: Buscar reglas
