products:
  arcs:
    name: Arcs

  ahoy:
    name: Ahoy

  oath:
    name: Oath

  root:
    name: Root

languages:
  de-DE:
    name: Deutsch

  en-US:
    name: English

  es-ES:
    name: Español

  nl-NL:
    name: Nederlands

  pl-PL:
    name: Polski

  pt-BR:
    name: Português

  ru-RU:
    name: Russian
