App:
  NavTitle: Updated Oct 8th, 2025
  NavTitleShort: Oct 8, 2025
  NoItemsFound: No items found.
  NoRulesAvailable: No rules available.
  SearchPlaceholder: Search Rules
  Locale:
    ShowRules: Show Rules
    ShowFAQ: Show FAQ
    ShowErrata: Show Errata
  Titles:
    Search: Search Rules
  About:
    ModalTitle: Other Links
    CardLibrary: Card Library
    GitHub: GitHub
    Discord: Discord
    LederSupport: Leder Games Support
