App:
  NavTitle: 3rd (Base) / 2nd (Blighted Reach)
  NavTitleShort: 3rd Print
  NoItemsFound: No items found.
  NoRulesAvailable: No rules available.
  SearchPlaceholder: Search Rules
  Locale:
    ShowRules: Show Rules
    ShowFAQ: Show FAQ
    ShowErrata: Show Errata
  Titles:
    Search: Search Rules
  About:
    ModalTitle: Other Links
    CardLibrary: Card Library
    GitHub: GitHub
    Discord: Discord
    LederSupport: Leder Games Support
