App:
  NavTitle: Правила и фракции
  NavTitleShort: Правила
  NoItemsFound: Ничего не найдено.
  NoRulesAvailable: Правила отсутствуют.
  SearchPlaceholder: Поиск в правилах
  Locale:
    ShowRules: Показать правила
    ShowFAQ: Показать FAQ
    ShowErrata: Показать Errata
  Titles:
    Search: Поиск
